version: "{build} ({branch})"

clone_folder: C:\projects\maven-compass-example

environment:
  MVN_VERSION: 3.3.3

  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
- set PATH=%PATH%;C:\tools\apache-maven-%MVN_VERSION%\bin
- IF NOT exist "C:\tools\apache-maven-%MVN_VERSION%\bin\*.*" (echo Maven %MVN_VERSION% not installed, so install it & cinst maven -Version %MVN_VERSION%) ELSE (echo  Maven %MVN_VERSION% already installed)

cache:
- C:\Users\appveyor\.m2\repository -> pom.xml
- C:\tools\apache-maven-%MVN_VERSION% -> appveyor.yml

build_script:
- cd C:\projects\maven-compass-example
- mvn -e -U -fae install site
