version: "{build} ({branch})"

clone_folder: C:\projects\maven-compass-example

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

cache:
  - C:\Users\appveyor\.m2\repository -> pom.xml

build_script:
  - cd C:\projects\maven-compass-example
  - mvn -v -e -fae install site
